FROM java:8
MAINTAINER javaonfly
COPY /target/nwt-izostanak-service-0.0.1-SNAPSHOT.jar /opt/lib/
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/lib/nwt-izostanak-service-0.0.1-SNAPSHOT.jar"]
EXPOSE 8002
